import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';

/**
 * Growlith Engine — ESLint flat config.
 *
 * `eslint-config-next/core-web-vitals` is the superset entry point: it requires
 * `./index`, which already bundles next, react, react-hooks, jsx-a11y, import
 * and the `next/typescript` (typescript-eslint) rule sets. Importing it once
 * avoids duplicated/conflicting config arrays.
 *
 * The `growlith/*` blocks below are not style preferences — several of them are
 * SECURITY CONTROLS. In this architecture the boundary between isomorphic code
 * (`src/lib`, `components`) and secret-bearing server code (`src/server`) is
 * enforced by three independent mechanisms, of which this file is one:
 *
 *   1. lint  (this file)          — fails CI on a structural violation
 *   2. build (`server-only`)      — fails the bundle if a server module is
 *                                   reachable from a client graph
 *   3. test  (tests/architecture) — fails on directive-level violations that
 *                                   static import patterns cannot see, e.g. a
 *                                   `'use client'` file importing `@/server/*`,
 *                                   plus a post-build scan of emitted chunks
 *
 * Do not weaken these rules without an ADR.
 */
const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'coverage/**',
      'dist/**',
      'build/**',
      'next-env.d.ts',
      'supabase/.temp/**',
      // Generated by `npm run db:types`. Linting generated output produces
      // noise and can mask real signal.
      'src/types/database.ts',
    ],
  },

  ...nextCoreWebVitals,

  /* ── Growlith: escalate the type-safety rules this architecture relies on ── */
  {
    name: 'growlith/typescript-strictness',
    // Scoped deliberately. In flat config a rule reference requires the plugin
    // to be registered for that file, and `eslint-config-next` registers
    // `@typescript-eslint` only for TypeScript files. Leaving this block
    // unscoped makes ESLint fail outright on `eslint.config.mjs` itself.
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      // `any` defeats the entire point of strict TypeScript in an authorization
      // system: it is how a role check gets bypassed at compile time.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'all' },
      ],
    },
  },

  /* ── SECURITY CONTROL: isomorphic code must never reach server-only code ── */
  {
    name: 'growlith/wall-lib-and-components',
    files: ['src/lib/**/*.{ts,tsx}', 'components/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@/server', '@/server/*', 'server-only', '**/src/server/*'],
              message:
                'src/lib/** and components/** are isomorphic and must be provably secret-free. ' +
                'Importing @/server/* would put SUPABASE_SERVICE_ROLE_KEY (which holds BYPASSRLS) ' +
                'within reach of the browser bundle. Move shared code to src/lib, or perform the ' +
                'work in a route handler / server component. See ADR-0002 and docs §M.',
            },
          ],
        },
      ],
      // Isomorphic modules may only read the environment through
      // `@/lib/env/client-env`, which validates that every key it reads is
      // NEXT_PUBLIC_. A bare `process.env.FOO` here compiles to `undefined` in
      // the browser — a silent failure that is hard to trace.
      'no-restricted-properties': [
        'error',
        {
          object: 'process',
          property: 'env',
          message:
            'Read environment through @/lib/env/client-env (isomorphic) or @/server/env (server-only). ' +
            'Direct process.env access defeats startup validation and can silently yield undefined in the browser.',
        },
      ],
      'no-restricted-globals': [
        'error',
        {
          name: 'process',
          message: 'Use @/lib/env/client-env instead of touching process.env in isomorphic code.',
        },
      ],
    },
  },

  // The one isomorphic module permitted to read NEXT_PUBLIC_* variables.
  {
    name: 'growlith/env-client-exception',
    files: ['src/lib/env/**/*.ts'],
    rules: {
      'no-restricted-properties': 'off',
      'no-restricted-globals': 'off',
    },
  },

  /* ── SECURITY CONTROL: server modules must not depend on the UI layer ── */
  {
    name: 'growlith/wall-server-no-ui',
    files: ['src/server/**/*.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@/components', '@/components/*', '**/components/*'],
              message:
                'Server modules must not import UI components: it inverts the dependency ' +
                'direction and drags React into the request path. Return data and let the ' +
                'presentation layer render it.',
            },
          ],
        },
      ],
    },
  },

  /* ── OBSERVABILITY CONTROL: all logging goes through the structured logger ──
     Unstructured console output has no requestId correlation and no secret
     redaction, so a stray console.log can write a JWT or a key to stdout.     */
  {
    name: 'growlith/no-raw-console',
    files: ['src/**/*.{ts,tsx}', 'app/**/*.{ts,tsx}', 'components/**/*.{ts,tsx}'],
    rules: {
      // No options object: ESLint requires `allow` to be non-empty, and the
      // intent here is a total ban outside the logger implementation.
      'no-console': 'error',
    },
  },
  {
    name: 'growlith/logger-implementation-exception',
    files: ['src/server/logging/**/*.ts'],
    rules: {
      'no-console': 'off',
    },
  },

  /* ── Node-authored ESM files (scripts, configs) ─────────────────────────── */
  {
    name: 'growlith/node-scripts',
    files: ['scripts/**/*.mjs', '*.config.mjs'],
    languageOptions: {
      sourceType: 'module',
      globals: {
        process: 'readonly',
        console: 'readonly',
        Buffer: 'readonly',
        URL: 'readonly',
        __dirname: 'readonly',
      },
    },
    rules: {
      'no-console': 'off',
    },
  },
];

export default config;
